services:
  database:
    image: mariadb:lts-ubi9
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: issue-tracker
      MARIADB_USER: issue-tracker
      MARIADB_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:

